/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moduloanalises;

/**
 *
 * @author Rafael
 */
public class Analises extends javax.swing.JFrame {

    /**
     * Creates new form Analises
     */
    public Analises() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogMenuAnalises = new javax.swing.JDialog();
        jPanelMenuAnilises = new javax.swing.JPanel();
        jButtonNovaAnalise = new javax.swing.JButton();
        jButtonConsultarAnalises = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();

        jDialogMenuAnalises.setMinimumSize(new java.awt.Dimension(413, 244));

        jButtonNovaAnalise.setText("Nova Analise");

        jButtonConsultarAnalises.setText("Consultar Analises");

        javax.swing.GroupLayout jPanelMenuAnilisesLayout = new javax.swing.GroupLayout(jPanelMenuAnilises);
        jPanelMenuAnilises.setLayout(jPanelMenuAnilisesLayout);
        jPanelMenuAnilisesLayout.setHorizontalGroup(
            jPanelMenuAnilisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuAnilisesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButtonNovaAnalise)
                .addGap(38, 38, 38)
                .addComponent(jButtonConsultarAnalises)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanelMenuAnilisesLayout.setVerticalGroup(
            jPanelMenuAnilisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuAnilisesLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanelMenuAnilisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovaAnalise)
                    .addComponent(jButtonConsultarAnalises))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogMenuAnalisesLayout = new javax.swing.GroupLayout(jDialogMenuAnalises.getContentPane());
        jDialogMenuAnalises.getContentPane().setLayout(jDialogMenuAnalisesLayout);
        jDialogMenuAnalisesLayout.setHorizontalGroup(
            jDialogMenuAnalisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMenuAnalisesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenuAnilises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogMenuAnalisesLayout.setVerticalGroup(
            jDialogMenuAnalisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMenuAnalisesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenuAnilises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonEntrar.setText("Entrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButtonEntrar)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jButtonEntrar)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analises().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarAnalises;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonNovaAnalise;
    private javax.swing.JDialog jDialogMenuAnalises;
    private javax.swing.JPanel jPanelMenuAnilises;
    // End of variables declaration//GEN-END:variables
}
