/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package moduloinsectocacadores;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Rafael
 */
public class Insectocadores extends javax.swing.JFrame {

    /* VARIAVEIS PARA A LIGAÇÃO A BASE DE DADOS */
    String url = "jdbc:derby://localhost:1527/equipamentos";
    Connection con;
    String sql;
    
    DefaultTableModel model;
    
    
    
    /**
     * Creates new form Insectocadores
     */
    public Insectocadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogMenuInsectocacadores = new javax.swing.JDialog();
        jPanelMenuInsectocadores = new javax.swing.JPanel();
        jButtonNovoInsecto = new javax.swing.JButton();
        jButtonConsultaInsecto = new javax.swing.JButton();
        jDialogNovoInsectocacador = new javax.swing.JDialog();
        jPanelNovoInsectocacador = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelReferencia = new javax.swing.JLabel();
        jLabelLocal = new javax.swing.JLabel();
        jTextFieldReferenciaInsecto = new javax.swing.JTextField();
        jTextFieldNomeInsecto = new javax.swing.JTextField();
        jTextFieldLocalInsecto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonGuardarInsecto = new javax.swing.JButton();
        jButtonSairInsecto = new javax.swing.JButton();
        jDialogConsultaInsectocacadores = new javax.swing.JDialog();
        jPanelConsultaInsecto = new javax.swing.JPanel();
        jScrollPaneConsultInsecto = new javax.swing.JScrollPane();
        jTableConsultaInsecto = new javax.swing.JTable();
        jButtonAddNovoInsecto = new javax.swing.JButton();
        jButtonSairConsultaInsecto = new javax.swing.JButton();
        jPanelLoginInsectocadores = new javax.swing.JPanel();
        jButtonEntrar = new javax.swing.JButton();

        jDialogMenuInsectocacadores.setMinimumSize(new java.awt.Dimension(593, 392));

        jButtonNovoInsecto.setText("Novo Insectocaçador");
        jButtonNovoInsecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoInsectoActionPerformed(evt);
            }
        });

        jButtonConsultaInsecto.setText("Consulta Insectocaçadores");
        jButtonConsultaInsecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaInsectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuInsectocadoresLayout = new javax.swing.GroupLayout(jPanelMenuInsectocadores);
        jPanelMenuInsectocadores.setLayout(jPanelMenuInsectocadoresLayout);
        jPanelMenuInsectocadoresLayout.setHorizontalGroup(
            jPanelMenuInsectocadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuInsectocadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNovoInsecto)
                .addGap(71, 71, 71)
                .addComponent(jButtonConsultaInsecto)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanelMenuInsectocadoresLayout.setVerticalGroup(
            jPanelMenuInsectocadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuInsectocadoresLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanelMenuInsectocadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovoInsecto)
                    .addComponent(jButtonConsultaInsecto))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogMenuInsectocacadoresLayout = new javax.swing.GroupLayout(jDialogMenuInsectocacadores.getContentPane());
        jDialogMenuInsectocacadores.getContentPane().setLayout(jDialogMenuInsectocacadoresLayout);
        jDialogMenuInsectocacadoresLayout.setHorizontalGroup(
            jDialogMenuInsectocacadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMenuInsectocacadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenuInsectocadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jDialogMenuInsectocacadoresLayout.setVerticalGroup(
            jDialogMenuInsectocacadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMenuInsectocacadoresLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanelMenuInsectocadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jDialogNovoInsectocacador.setTitle("NOVO INSECTOCAÇADOR");
        jDialogNovoInsectocacador.setMinimumSize(new java.awt.Dimension(352, 306));

        jLabelNome.setText("Nome");

        jLabelReferencia.setText("Referencia");

        jLabelLocal.setText("Local");

        jTextFieldNomeInsecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeInsectoActionPerformed(evt);
            }
        });

        jLabel1.setText("Novo Insectocaçador");

        jButtonGuardarInsecto.setText("Guardar");

        jButtonSairInsecto.setText("Sair");
        jButtonSairInsecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairInsectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNovoInsectocacadorLayout = new javax.swing.GroupLayout(jPanelNovoInsectocacador);
        jPanelNovoInsectocacador.setLayout(jPanelNovoInsectocacadorLayout);
        jPanelNovoInsectocacadorLayout.setHorizontalGroup(
            jPanelNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNovoInsectocacadorLayout.createSequentialGroup()
                .addGroup(jPanelNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNovoInsectocacadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonGuardarInsecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSairInsecto))
                    .addGroup(jPanelNovoInsectocacadorLayout.createSequentialGroup()
                        .addGroup(jPanelNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNovoInsectocacadorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelReferencia)
                                    .addComponent(jLabelNome)
                                    .addComponent(jLabelLocal))
                                .addGap(31, 31, 31)
                                .addGroup(jPanelNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNomeInsecto, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(jTextFieldLocalInsecto))
                                    .addComponent(jTextFieldReferenciaInsecto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelNovoInsectocacadorLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNovoInsectocacadorLayout.setVerticalGroup(
            jPanelNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNovoInsectocacadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelReferencia)
                    .addComponent(jTextFieldReferenciaInsecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanelNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNomeInsecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocal)
                    .addComponent(jTextFieldLocalInsecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarInsecto)
                    .addComponent(jButtonSairInsecto))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogNovoInsectocacadorLayout = new javax.swing.GroupLayout(jDialogNovoInsectocacador.getContentPane());
        jDialogNovoInsectocacador.getContentPane().setLayout(jDialogNovoInsectocacadorLayout);
        jDialogNovoInsectocacadorLayout.setHorizontalGroup(
            jDialogNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNovoInsectocacadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNovoInsectocacador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jDialogNovoInsectocacadorLayout.setVerticalGroup(
            jDialogNovoInsectocacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNovoInsectocacadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNovoInsectocacador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jDialogConsultaInsectocacadores.setTitle("CONSULTA INSECTOCADORES");
        jDialogConsultaInsectocacadores.setMinimumSize(new java.awt.Dimension(672, 412));

        jTableConsultaInsecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Referencia", "Nome", "Local"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneConsultInsecto.setViewportView(jTableConsultaInsecto);

        jButtonAddNovoInsecto.setText("Novo Insecto.");

        jButtonSairConsultaInsecto.setText("Voltar");
        jButtonSairConsultaInsecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairConsultaInsectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultaInsectoLayout = new javax.swing.GroupLayout(jPanelConsultaInsecto);
        jPanelConsultaInsecto.setLayout(jPanelConsultaInsectoLayout);
        jPanelConsultaInsectoLayout.setHorizontalGroup(
            jPanelConsultaInsectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaInsectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaInsectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneConsultInsecto, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(jPanelConsultaInsectoLayout.createSequentialGroup()
                        .addComponent(jButtonAddNovoInsecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSairConsultaInsecto)))
                .addContainerGap())
        );
        jPanelConsultaInsectoLayout.setVerticalGroup(
            jPanelConsultaInsectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaInsectoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPaneConsultInsecto, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelConsultaInsectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddNovoInsecto)
                    .addComponent(jButtonSairConsultaInsecto))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogConsultaInsectocacadoresLayout = new javax.swing.GroupLayout(jDialogConsultaInsectocacadores.getContentPane());
        jDialogConsultaInsectocacadores.getContentPane().setLayout(jDialogConsultaInsectocacadoresLayout);
        jDialogConsultaInsectocacadoresLayout.setHorizontalGroup(
            jDialogConsultaInsectocacadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogConsultaInsectocacadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConsultaInsecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jDialogConsultaInsectocacadoresLayout.setVerticalGroup(
            jDialogConsultaInsectocacadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogConsultaInsectocacadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConsultaInsecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginInsectocadoresLayout = new javax.swing.GroupLayout(jPanelLoginInsectocadores);
        jPanelLoginInsectocadores.setLayout(jPanelLoginInsectocadoresLayout);
        jPanelLoginInsectocadoresLayout.setHorizontalGroup(
            jPanelLoginInsectocadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginInsectocadoresLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButtonEntrar)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanelLoginInsectocadoresLayout.setVerticalGroup(
            jPanelLoginInsectocadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginInsectocadoresLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButtonEntrar)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanelLoginInsectocadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanelLoginInsectocadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeInsectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeInsectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeInsectoActionPerformed

    private void jButtonNovoInsectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoInsectoActionPerformed
        // BOTAO NOVO INSECTOCAÇADOR -> JANELA MENU 
        jDialogNovoInsectocacador.setLocationRelativeTo(this);
        jDialogNovoInsectocacador.setVisible(true);
    }//GEN-LAST:event_jButtonNovoInsectoActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        // BOTAO ENTRAR -> JANELA DE LOGIN
        jDialogMenuInsectocacadores.setLocationRelativeTo(this);
        jDialogMenuInsectocacadores.setVisible(true);
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonSairInsectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairInsectoActionPerformed
        // BOTAO SAIR -> JANELA NOVO INSECTOCAÇADOR
        jDialogNovoInsectocacador.setVisible(false);
        LimpaCamposNovoInsectocador();
    }//GEN-LAST:event_jButtonSairInsectoActionPerformed

    private void jButtonSairConsultaInsectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairConsultaInsectoActionPerformed
        // BOTAO SAIR -> JANELA CONSULTA INSECTOCADORES
        jDialogConsultaInsectocacadores.setVisible(false);
    }//GEN-LAST:event_jButtonSairConsultaInsectoActionPerformed

    private void jButtonConsultaInsectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaInsectoActionPerformed
        // BOTAO CONSULTA INSECTOCACADORES -> JANELA MENU
        jDialogConsultaInsectocacadores.setLocationRelativeTo(this);
        jDialogConsultaInsectocacadores.setVisible(true);
    }//GEN-LAST:event_jButtonConsultaInsectoActionPerformed

    
    
    
    
    
    
    /*  ************************************************* FUNÇOES **************************************** */
    
    /*  INSERIR */
    private void InserirNovoInsecto(){
        String referencia = jTextFieldReferenciaInsecto.getText();
        String nome = jTextFieldNomeInsecto.getText();
        String local = jTextFieldLocalInsecto.getText();
        
        try {
                Class.forName("org.apache.derby.jdbc.ClientDriver");
            } catch (ClassNotFoundException e) { //driver não encontrado
                System.err.print("ClassNotFoundException: ");
                System.err.println(e.getMessage());
                System.out.println("O driver expecificado nao foi encontrado.");
            }
            try {
                con = DriverManager.getConnection(url);
                String nomeTabela = "MANUTENCAOEQUIPAMENTOS";
                sql = "INSERT INTO " + nomeTabela + "(IDEQUIPAMENTO,DATA,OBSERVACOES,FICHATECNICA)" + " values("+ idEquip + "," + "'" + data + "'" + "," + "'" + observacoes + "'"+"," + "'" + fichaTecnica+ "'"  + ")";

                PreparedStatement st = (PreparedStatement) con.prepareStatement(sql);
                st.executeUpdate();
                st.close();
                con.close();
            } catch (SQLException ex) {
                System.err.println("SQLException: " + ex.getMessage());
            }
        
            System.out.println("\n*** INSERIR NOVA MANUTENÇÃO -> VINDA DA CONSULTA DOS EQUIPAMETNO");
            System.out.println("ID EQUIPAMENTO SELECIONADO: " + idEquip);
            System.out.println("DATA: " + data);
            System.out.println("OBSERVAÇÕES: " + observacoes);
        
    }
    
    
    
    
    /*  LIMPAR  */
    
    private void LimpaCamposNovoInsectocador(){
        jTextFieldLocalInsecto.setText("");
        jTextFieldNomeInsecto.setText("");
        jTextFieldReferenciaInsecto.setText("");
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insectocadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insectocadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insectocadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insectocadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insectocadores().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNovoInsecto;
    private javax.swing.JButton jButtonConsultaInsecto;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonGuardarInsecto;
    private javax.swing.JButton jButtonNovoInsecto;
    private javax.swing.JButton jButtonSairConsultaInsecto;
    private javax.swing.JButton jButtonSairInsecto;
    private javax.swing.JDialog jDialogConsultaInsectocacadores;
    private javax.swing.JDialog jDialogMenuInsectocacadores;
    private javax.swing.JDialog jDialogNovoInsectocacador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLocal;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelReferencia;
    private javax.swing.JPanel jPanelConsultaInsecto;
    private javax.swing.JPanel jPanelLoginInsectocadores;
    private javax.swing.JPanel jPanelMenuInsectocadores;
    private javax.swing.JPanel jPanelNovoInsectocacador;
    private javax.swing.JScrollPane jScrollPaneConsultInsecto;
    private javax.swing.JTable jTableConsultaInsecto;
    private javax.swing.JTextField jTextFieldLocalInsecto;
    private javax.swing.JTextField jTextFieldNomeInsecto;
    private javax.swing.JTextField jTextFieldReferenciaInsecto;
    // End of variables declaration//GEN-END:variables
}
